### ISSUE TITLE
Change namespace

### ISSUE THREAD

**Issue by pine** [mattak/AspectRatioLayout#10]
Why does this namespace include underscore ?

**Comment by mattak** [comment]
Do you mean `me.mattak.aspect_ratio_layout` to `me.mattak.aspectratiolayout` ?
It seems to be difficult to read and typing.
And [Java is tolerance using package name underscore](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

So if change the packagename, I think more shorten one is better to replace with.

**Comment by pine** [comment]
oh... That's right.
